version: "2"
services:
    php:
        container_name: dotfiles.php
        build:
            context: docker
        volumes:
            - ./.git:/app/.git:ro
            - ./bin:/app/bin:ro
            - ./features:/app/features:ro
            - ./src:/app/src:ro
            - ./vendor:/app/vendor:ro
            - /app/build
            - /app/var
            - ./:/home/dotfiles:ro
