<?php

declare(strict_types=1);

/*
 * This file is part of the dotfiles project.
 *
 *     (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Dotfiles\Core\Tests\Console;

use Dotfiles\Core\Config\Config;
use Dotfiles\Core\Console\Output;
use PHPUnit\Framework\TestCase;

class TestOutput extends Output
{
    public function __construct(Config $config)
    {
        parent::__construct($config);
    }

    public function write($messages, $newline = false, $options = \Symfony\Component\Console\Output\Output::OUTPUT_NORMAL): void
    {
        parent::write($messages, $newline, $options); // TODO: Change the autogenerated stub
    }

    /**
     * Returns true if current environment supports writing console output to
     * STDOUT.
     *
     * @return bool
     */
    protected function hasStdoutSupport()
    {
        return false;
    }
}

/**
 * Class OutputTest.
 *
 * @covers \Dotfiles\Core\Console\Output
 */
class OutputTest extends TestCase
{
    public function testWriteStripFileName(): void
    {
        $tempDir = sys_get_temp_dir().'/dotfiles/tests/output';

        $config = $this->createMock(Config::class);
        $config->expects($this->any())
            ->method('get')
            ->willReturnMap(array(
                array('dotfiles.home_dir', $tempDir.'/home'),
                array('dotfiles.repo_dir', $tempDir.'/repo'),
                array('dotfiles.temp_dir', $tempDir.'/temp'),
                array('dotfiles.bin_dir', $tempDir.'/bin'),
            ));
        $output = new TestOutput($config);

        ob_start();
        $output->writeln($tempDir.'/home/foo/bar');
        $output->writeln($tempDir.'/repo/foo/bar');
        $output->writeln($tempDir.'/bin/some-command');
        $display = ob_get_contents();
        ob_end_clean();

        $this->assertContains('foo/bar', $display);
        $this->assertContains('bin/some-command', $display);
    }
}
