export PATH="$PATH:$HOME/dotfiles/bin"
#export EDITOR=/usr/bin/vim
#export VISUAL=/usr/bin/vim

export THEME_SHOW_SUDO=true
export THEME_SHOW_SCM=true
export THEME_SHOW_CLOCK=false
export THEME_SHOW_EXITCODE=true
export THEME_SHOW_RUBY=false
export BASH_IT_THEME='atomic'
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1
export GIT_HOSTING='git@bitbucket.org'

export PHPBREW_SET_PROMPT=1
export PHPBREW_RC_ENABLE=1
source $HOME/.phpbrew/bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
