services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Dotfiles\Core\Application: ~
    Dotfiles\Core\Event\Dispatcher: ~
    Dotfiles\Core\Config\Config:
        synthetic: true
        calls:
            - [setCachePath, ['%dotfiles.cache_dir%']]
    Dotfiles\Core\Command\InstallCommand:
        tags: { name: dotfiles.command }
    Dotfiles\Core\Command\SelfUpdateCommand:
        tags: { name: dotfiles.command }
    dotfiles.app:
        alias: Dotfiles\Core\Application
    dotfiles.config:
        alias: Dotfiles\Core\Config\Config
