services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Dotfiles\Core\Event\Dispatcher: ~
    Dotfiles\Core\Config\Config:
        synthetic: true
        calls:
            - [setCachePath, ['%dotfiles.cache_dir%']]
    Dotfiles\Core\Command\InstallCommand: ~
    Dotfiles\Core\Command\BackupCommand: ~
    Dotfiles\Core\Command\SelfUpdateCommand: ~
    Dotfiles\Core\Command\ClearCacheCommand: ~
    Dotfiles\Core\Command\AddCommand: ~
    Dotfiles\Core\Application: ~
    Dotfiles\Core\Util\CommandProcessor: ~

    # aliasses
    Psr\Log\LoggerInterface:
        alias: dotfiles.logger
    Dotfiles\Core\Util\Downloader:
        alias: dotfiles.downloader
    dotfiles.app:
        alias: Dotfiles\Core\Application
    dotfiles.config:
        alias: Dotfiles\Core\Config\Config
    dotfiles.input:
        class: Symfony\Component\Console\Input\ArgvInput
    dotfiles.output:
        class: Symfony\Component\Console\Output\ConsoleOutput
    dotfiles.logger:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments: ['@dotfiles.output']
    dotfiles.downloader:
        class: Dotfiles\Core\Util\Downloader
        arguments: ['@dotfiles.output','@dotfiles.logger']

    Symfony\Component\Console\Input\InputInterface:
        alias: dotfiles.input
    Symfony\Component\Console\Output\OutputInterface:
        alias: dotfiles.output
