services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
                
    Dotfiles\Core\Processor\Restore:
        alias: dotfiles.restore
    Dotfiles\Core\Event\Dispatcher: ~
    Dotfiles\Core\Config\Config:
        synthetic: true
        calls:
            - [setCachePath, ['%dotfiles.cache_dir%']]
    Dotfiles\Core\Command\SelfUpdateCommand: ~
    Dotfiles\Core\Command\ClearCacheCommand: ~
    Dotfiles\Core\Command\AddCommand: ~
    Dotfiles\Core\Command\InitCommand: ~
    Dotfiles\Core\Command\RestoreCommand: ~
    Dotfiles\Core\Command\ConfigCommand: ~
    Dotfiles\Core\Application: ~
    Dotfiles\Core\Util\CommandProcessor: ~
    Dotfiles\Core\Util\Filesystem: ~

    # aliasses
    Psr\Log\LoggerInterface:
        alias: dotfiles.logger
    Dotfiles\Core\Util\Downloader:
        alias: dotfiles.downloader
    dotfiles.app:
        alias: Dotfiles\Core\Application
    dotfiles.config:
        alias: Dotfiles\Core\Config\Config
    dotfiles.input:
        class: Dotfiles\Core\Console\Input
    dotfiles.output:
        class: Dotfiles\Core\Console\Output
    dotfiles.logger:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments: ['@dotfiles.output']
    dotfiles.downloader:
        class: Dotfiles\Core\Util\Downloader
        arguments: ['@dotfiles.output','@dotfiles.logger']
    dotfiles.restore:
        class: Dotfiles\Core\Processor\Restore

    Symfony\Component\Console\Input\InputInterface:
        alias: dotfiles.input
    Symfony\Component\Console\Output\OutputInterface:
        alias: dotfiles.output
