services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Dotfiles\Core\Event\Dispatcher: ~
    Dotfiles\Core\Command\SelfUpdateCommand: ~
    Dotfiles\Core\Command\ClearCacheCommand: ~
    Dotfiles\Core\Command\AddCommand: ~
    Dotfiles\Core\Command\InitCommand: ~
    Dotfiles\Core\Command\RestoreCommand: ~
    Dotfiles\Core\Command\ConfigCommand: ~
    Dotfiles\Core\Command\ShellCommand: ~
    Dotfiles\Core\Console\Application: ~
    Dotfiles\Core\Console\Shell: ~
    Dotfiles\Core\Processor\ProcessRunner: ~
    Dotfiles\Core\Util\Filesystem: ~
    Dotfiles\Core\ApplicationFactory: ~

    # aliasses
    Psr\Log\LoggerInterface:
        alias: dotfiles.logger
    Dotfiles\Core\Util\Downloader:
        alias: dotfiles.downloader
    dotfiles.factory:
        class: Dotfiles\Core\ApplicationFactory
    dotfiles.app:
        alias: Dotfiles\Core\Console\Application
    dotfiles.input:
        class: Dotfiles\Core\Console\Input
    dotfiles.output:
        class: Dotfiles\Core\Console\Output
    dotfiles.logger:
        class: Dotfiles\Core\Console\ConsoleLogger
    dotfiles.parameters:
        class: Dotfiles\Core\DI\Parameters
        synthetic: true
    Dotfiles\Core\DI\Parameters:
        alias: dotfiles.parameters
        
    dotfiles.downloader:
        class: Dotfiles\Core\Util\Downloader
        arguments: ['@dotfiles.output','@dotfiles.logger']

    Symfony\Component\Console\Input\InputInterface:
        alias: dotfiles.input
    Symfony\Component\Console\Output\OutputInterface:
        alias: dotfiles.output
        
    # processor service
    dotfiles.hooks:
        class: Dotfiles\Core\Processor\Hooks
    dotfiles.template:
        class: Dotfiles\Core\Processor\Template
    dotfiles.patcher:
        class: Dotfiles\Core\Processor\Patcher
    Dotfiles\Core\Processor\Patcher:
        alias: dotfiles.patcher
    Dotfiles\Core\Processor\Hooks:
        alias: dotfiles.hooks
    Dotfiles\Core\Processor\Template:
        alias: dotfiles.template
